name: agenda-java21-mysql

services:
  db:
    image: mysql:8.4
    container_name: agenda_db
    restart: always
    environment:
      MYSQL_DATABASE: agenda_db
      MYSQL_ROOT_PASSWORD: root_password
    ports:
      - "3315:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    image: eclipse-temurin:21-jdk-jammy
    container_name: agenda_app
    volumes:
      - .:/app
    working_dir: /app
    stdin_open: true
    tty: true
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_NAME=agenda_db
      - DB_USER=root
      - DB_PASS=root_password

volumes:
  mysql_data: