CREATE TABLE IF NOT EXISTS event (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(100) NOT NULL,
    description VARCHAR(255),
    event_date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
)